//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTCustomerProfiles
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESTEntities : DbContext
    {
        public ESTEntities()
            : base("name=ESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Guideline> Guidelines { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<Severity_Action> Severity_Actions { get; set; }
        public virtual DbSet<Support> Supports { get; set; }
        public virtual DbSet<Supported_Severity> Supported_Severities { get; set; }
    }
}
