//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTCustomerProfiles
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int customerId { get; set; }
        public System.DateTime holiday1 { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
