//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTCustomerProfiles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int contactId { get; set; }
        public int customerId { get; set; }
        public string name { get; set; }
        public string designation { get; set; }
        public string email { get; set; }
        public string workPhone { get; set; }
        public string mobile { get; set; }
        public string additionalInfo { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
