//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTCustomerProfiles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Contacts = new HashSet<Contact>();
            this.Holidays = new HashSet<Holiday>();
            this.Supports = new HashSet<Support>();
            this.Supported_Severities = new HashSet<Supported_Severity>();
        }
    
        public int customerId { get; set; }
        public string customerName { get; set; }
        public string documentPath { get; set; }
        public string spptOrganization { get; set; }
        public Nullable<decimal> offset { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual Guideline Guideline { get; set; }
        public virtual ICollection<Holiday> Holidays { get; set; }
        public virtual Severity_Action Severity_Action { get; set; }
        public virtual ICollection<Support> Supports { get; set; }
        public virtual ICollection<Supported_Severity> Supported_Severities { get; set; }
    }
}
