//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTCustomerProfiles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Severity_Action
    {
        public int customerId { get; set; }
        public string action1 { get; set; }
        public string action2 { get; set; }
        public string action3 { get; set; }
        public string action4 { get; set; }
        public string additionalInfo { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
