//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESTCustomerProfiles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        public int customerId { get; set; }
        public int supportKey { get; set; }
        public string description { get; set; }
        public string queue { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
